version: '3.7'

services: 
  db:
    image: 'mysql:8.0.22'
    container_name: mysqldb
    ports: 
      - "3306:3306"
      
volumes: 
  springboot-task-tracker-mysql-api-volume:

networks:
  default:
    name: springboot-task-tracker-mysql-api-network